In [2]:
import pandas as pd

In [3]:
sales = pd.read_csv("Sales-Export_2019-2020.csv")

In [4]:
sales.head(3)

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341

In [5]:
sales.shape

(1000, 10)

In [6]:
sales.columns

Index(['country', ' order_value_EUR ', ' cost ', 'date', 'category',
       'customer_name', 'sales_manager', 'sales_rep', 'device_type',
       'order_id'],
      dtype='object')

In [7]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country            1000 non-null   object
 1    order_value_EUR   1000 non-null   object
 2    cost              1000 non-null   float64
 3   date               1000 non-null   object
 4   category           1000 non-null   object
 5   customer_name      1000 non-null   object
 6   sales_manager      1000 non-null   object
 7   sales_rep          1000 non-null   object
 8   device_type        1000 non-null   object
 9   order_id           1000 non-null   object
dtypes: float64(1), object(9)
memory usage: 78.3+ KB

In [12]:
sales.describe()

               cost
count    1000.000000
mean    94369.310990
std     51540.020934
min     12113.680000
25%     54247.957500
50%     87094.760000
75%    125570.837500
max    304701.430000

In [13]:
sales.isnull().sum()

country              0
 order_value_EUR     0
 cost                0
date                 0
category             0
customer_name        0
sales_manager        0
sales_rep            0
device_type          0
order_id             0
dtype: int64

In [14]:
sales.duplicated().sum()

np.int64(0)

In [15]:
sales.drop_duplicates()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,4/2/2020,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,12/22/2019,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160
...,...,...,...,...,...,...,...,...,...,...
995,France,"46,296.26",40319.41,5/15/2020,Games,Wisoky Inc,Othello Bowes,Amelina Piscopiello,Tablet,77-3489084
996,Belgium,"118,061.05",101131.10,7/2/2020,Appliances,Johns and Sons,Lambert Norheny,Collin Mackness,Mobile,59-2117058
997,Finland,"74,480.56",60023.88,3/6/2020,Clothing,Homenick-Marvin,Hube Corey,Wat Bowkley,PC,31-1849120
998,Spain,"87,205.01",69171.01,6/18/2020,Games,Johns and Sons,Emalia Dinse,Manuel Goudie,Tablet,45-3085595
999,Portugal,"107,716.72",86679.64,1/18/2020,Accessories,"Jacobson, Marvin and Brown",Celine Tumasian,Brynn Dempster,Mobile,61-3294149

In [17]:
sales.columns = (
    sales.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [20]:
sales = sales.rename(columns= {"date" : "datetime"})

In [22]:
sales.head(3)

,country,order_value_eur,cost,datetime,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341

In [23]:
categorical_cols = ['country', 'category', 'sales_manager', 'sales_rep', 'device_type']

sales[categorical_cols] = sales[categorical_cols].astype('category')

In [24]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          1000 non-null   category
 1   order_value_eur  1000 non-null   object
 2   cost             1000 non-null   float64
 3   datetime         1000 non-null   object
 4   category         1000 non-null   category
 5   customer_name    1000 non-null   object
 6   sales_manager    1000 non-null   category
 7   sales_rep        1000 non-null   category
 8   device_type      1000 non-null   category
 9   order_id         1000 non-null   object
dtypes: category(5), float64(1), object(4)
memory usage: 47.2+ KB

In [26]:
sales['order_value_eur'] = pd.to_numeric(
    sales['order_value_eur'].astype(str).str.replace(',', ''),
    errors='coerce'
)

In [27]:
sales['cost'] = pd.to_numeric(
    sales['cost'].astype(str).str.replace(',', ''),
    errors='coerce'
)

In [28]:
sales.dtypes

country            category
order_value_eur     float64
cost                float64
datetime             object
category           category
customer_name        object
sales_manager      category
sales_rep          category
device_type        category
order_id             object
dtype: object

In [29]:
sales.to_csv(
    "cleaned_sales_data.csv",
    index=False
)